In [1]:
import numpy as np

In [2]:
# creating an array
list=[]
arr=np.array(list)

In [3]:
arr
#look, implicitly the array takes up the floating pt. dtype

array([], dtype=float64)

In [4]:
type(arr)

numpy.ndarray

In [10]:
#explicitly defining the array
l=[1,2,3,4]
arr1=np.array(l)

In [17]:
#implicit method
arr2=np.array([1.2,1.3,2.4,2])

In [18]:
arr2

array([1.2, 1.3, 2.4, 2. ])

In [26]:
# typecasting the data 
list_1=[1.2,2.1,3.6,3.4,7]

arr3=np.array(list_1)

arr4=np.array(list_1,dtype='int32') # or dtype=int

print(arr3,'\n',arr4)

[1.2 2.1 3.6 3.4 7. ] 
 [1 2 3 3 7]


In [34]:
# ones and zeroes using numpy

arr5=np.zeros([2,2])

In [35]:
arr5

array([[0., 0.],
       [0., 0.]])

In [32]:
arr6=np.ones([2,3],dtype=int)
arr6

array([[1, 1, 1],
       [1, 1, 1]])

In [37]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr=np.arange(3,12,1.4) #the third column is the step
arr

array([ 3. ,  4.4,  5.8,  7.2,  8.6, 10. , 11.4])

In [43]:
arr=np.arange(10,step=2)
arr

array([0, 2, 4, 6, 8])

In [46]:
arr=np.linspace(1,10,51)
# np.linspace(start,end,no_of_datapoints)
arr

array([ 1.  ,  1.18,  1.36,  1.54,  1.72,  1.9 ,  2.08,  2.26,  2.44,
        2.62,  2.8 ,  2.98,  3.16,  3.34,  3.52,  3.7 ,  3.88,  4.06,
        4.24,  4.42,  4.6 ,  4.78,  4.96,  5.14,  5.32,  5.5 ,  5.68,
        5.86,  6.04,  6.22,  6.4 ,  6.58,  6.76,  6.94,  7.12,  7.3 ,
        7.48,  7.66,  7.84,  8.02,  8.2 ,  8.38,  8.56,  8.74,  8.92,
        9.1 ,  9.28,  9.46,  9.64,  9.82, 10.  ])

In [48]:
arr.shape

(51,)

In [49]:
#reshape

In [61]:
arr=np.arange(100,step=10)
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [62]:
arr[5:]=200
arr

array([  0,  10,  20,  30,  40, 200, 200, 200, 200, 200])

In [63]:
# used in EDA , rarely used way to detect the outliers!!
print(arr<70)
print(arr[arr<200])


print(arr//10)

print(arr+23)

[ True  True  True  True  True False False False False False]
[ 0 10 20 30 40]
[ 0  1  2  3  4 20 20 20 20 20]
[ 23  33  43  53  63 223 223 223 223 223]


In [55]:
arr=np.arange(0,50,5)
arr.shape

(10,)

In [58]:
arr=np.arange(100,step=10).reshape(2,5)
print(arr,'\n',arr.shape)

[[ 0 10 20 30 40]
 [50 60 70 80 90]] 
 (2, 5)


In [67]:
#random distribution
arr=np.random.rand(3,3)
arr

array([[0.06582366, 0.72637252, 0.05481447],
       [0.0298863 , 0.71841226, 0.32093984],
       [0.04641524, 0.29186966, 0.25362864]])

In [70]:
# normal distribution
arr_ex=np.random.randn(5,4)
arr_ex

array([[-0.51161468, -1.64753628,  1.12614572,  0.59705125],
       [ 1.27461902,  0.00410335,  0.28170494, -0.41330929],
       [-0.73798374,  0.63936007, -1.32682519, -0.34900611],
       [ 0.20481222, -0.6519574 , -0.45721608,  0.19494725],
       [ 1.48391182,  0.02626301, -0.15467253, -0.38902819]])

In [71]:
arr1=arr.copy()
arr1

array([[0.06582366, 0.72637252, 0.05481447],
       [0.0298863 , 0.71841226, 0.32093984],
       [0.04641524, 0.29186966, 0.25362864]])

In [75]:
np.random.randint(3,100,40)
# np.random.radint(start,end,no_of_datapt.)

array([65, 38, 45, 94,  3, 78, 67, 28, 54, 78, 20, 29, 63, 42,  6, 61, 95,
       50, 32, 98, 16, 28,  4, 33, 34, 19, 27, 99, 78, 32, 56, 72,  7, 88,
       31, 35, 70,  5, 23,  7])

In [87]:
'''Addition of matrices is possible if they of same shape
But numpy broadcasting allows to add different shapes with some conditions'''

arr1=np.arange(20).reshape(4,5)

arr2=np.arange(10,step=2)

print(arr1)
print(arr2)

print(arr1.shape,arr2.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[0 2 4 6 8]
(4, 5) (5,)


In [86]:
print(arr1+arr2)

[[ 0  3  6  9 12]
 [ 5  8 11 14 17]
 [10 13 16 19 22]
 [15 18 21 24 27]]


In [88]:
arr1=np.arange(20,100,20).reshape(4,5)
arr2=np.arange(16,step=4).reshape(1,4)

print(arr1+arr2)

ValueError: cannot reshape array of size 4 into shape (4,5)

In [102]:
arr1=np.random.randint(30,100,50).reshape(50,1)
arr2=np.random.randint(0,300,50).reshape(50,1)

arr3=np.stack((arr1,arr2),axis=0) 
# the axis=0 argument to stack the arrays vertically. Add an other row

In [103]:
arr3.shape  
#so it becomes 2 rows , 50 columns and depth of 2 

(2, 50, 1)

In [106]:
#COLUMN STACK
arr4=np.column_stack((arr1,arr2))
arr4.shape

(50, 2)

In [109]:

a = np.array([[3, 1], [4, 2]])

# Sort the array along the last axis
indices = np.argsort(a, axis=-1)

# Print the sorted indices
print(indices)


[[1 0]
 [1 0]]
